#!/opt/homebrew/bin/bash

# small script that clones one drive to another using rsync
# usage:
# clone --from <from> --to <to>

while [ $# -gt 0 ]; do
    if [[ $1 == "--"* ]]; then
        v="${1/--/}"
        declare "$v"="$2"
        shift
    fi
    shift
done

if [ -z ${from+x} ]; 
then 
    echo "--from is unset. Cannot proceed."; 
    exit 1;
fi

if [ -z ${to+x} ]; 
then 
    echo "--to is unset. Cannot proceed."; 
    exit 1;
fi

echo "Cloning from '$from' --> '$to'"


for folder in $from* ; do

    if [[ -d $folder ]]; then
        echo "$folder is a directory"
    elif [[ -f $folder ]]; then
        echo "$folder is a file, skipping..."
        continue
    else
        echo "$folder is not valid, skipping..."
        continue
    exit 1
    fi

    this_dest="${folder/"$from"/"$to"}" 

    printf "\n"
    printf "==========================================\n"
    echo $folder/ "-->" $this_dest/
    

    rsync -rahvzP --delete --ignore-existing $folder/ $this_dest/

done
